// Date: 11-Oct-16 17:24:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package io.github.herpahermaderp.japmythc.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelYamajijii extends ModelBase {
  
	//fields
    ModelRenderer eye;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer leg;
  
  public ModelYamajijii() {
    
	  textureWidth = 64;
	  textureHeight = 64;
    
      eye = new ModelRenderer(this, 2, 35);
      eye.addBox(-1F, 0F, 0F, 4, 3, 1);
      eye.setRotationPoint(-1F, -6F, -5F);
      eye.setTextureSize(64, 64);
      eye.mirror = true;
      setRotation(eye, 0F, 0F, 0F);
      head = new ModelRenderer(this, 1, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 17, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 29, 46);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, -0.5934119F, 0F, 0F);
      leftarm = new ModelRenderer(this, 12, 46);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, -0.5934119F, 0F, 0F);
      leg = new ModelRenderer(this, 0, 16);
      leg.addBox(-4F, 0F, -2F, 4, 12, 4);
      leg.setRotationPoint(2F, 12F, 0F);
      leg.setTextureSize(64, 64);
      leg.mirror = true;
      setRotation(leg, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    
	  super.render(entity, f, f1, f2, f3, f4, f5);
	  setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	  eye.render(f5);
	  head.render(f5);
	  body.render(f5);
	  rightarm.render(f5);
	  leftarm.render(f5);
	  leg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z) {
    
	  model.rotateAngleX = x;
	  model.rotateAngleY = y;
	  model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
    
	  super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
}
